### ISSUE TITLE
error deploying with -t parameter

### ISSUE THREAD

**Issue by xavs** [martinlevesque/openode-cli#1]
I'm having an issue when trying to deploy using the token parameter
```
openode  deploy -t {"token":"MYTOKENSTRING","site_name":"MYSITE"} 
SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at execSyncFiles (/usr/lib/node_modules/openode/modules/deploy.js:190:24)

```
And yes, it works when using the credential in the .openode file

**Comment by martinlevesque** [comment]
Note that the command format is the following:

`
openode deploy [--clearNpm] [-t TOKEN -s SITE_NAME]
`

so your command should be:

`
openode deploy -t MYTOKENSTRING -s MYSITE
`
